---
# Globals

app_name: 'angular-fe'
openshift_templates_raw: 'https://raw.githubusercontent.com/rht-labs/openshift-templates'
openshift_templates_raw_version_tag: 'v1.3.2'

build:
  NAME: '{{ app_name }}'

deploy:
  dev:
    PIPELINES_NAMESPACE: '{{ ci_cd_namespace }}'
    NAME: '{{ app_name }}'
    NAMESPACE: '{{ dev_namespace }}'
    CUSTOM_ENV: '{ apiUrl: "http://example-api-{{ dev_namespace }}.apps.{{ company_name }}.server.example.com"}'
  test:
    PIPELINES_NAMESPACE: '{{ ci_cd_namespace }}'
    NAME: '{{ app_name }}'
    NAMESPACE: '{{ test_namespace }}'
    CUSTOM_ENV: '{ apiUrl: "http://example-api-{{ test_namespace }}.apps.{{ company_name }}.server.example.com"}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: '{{ app_name }}-build'
        template: '{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/app-build/js-app-binary-build.yml'
        params_from_vars: '{{ build }}'
        namespace: '{{ ci_cd_namespace }}'
        tags:
          - build

  - object: deploy-dev
    content:
      - name: '{{ app_name }}-{{ dev_namespace }}-deploy'
        template: '{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/app-deploy/js-app-deploy-with-configmap.yml'
        params_from_vars: '{{ deploy.dev }}'
        namespace: '{{ dev_namespace }}'
        tags:
          - deploy
          - dev
  - object: deploy-test
    content:
      - name: '{{ app_name }}-{{ test_namespace }}-deploy'
        template: '{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/app-deploy/js-app-deploy-with-configmap.yml'
        params_from_vars: '{{ deploy.test }}'
        namespace: '{{ test_namespace }}'
        tags:
          - deploy
          - test
