---
- name: Build and Deploy angular-fe
  hosts: app
  vars:
    company_name: companyxyz
    ci_cd_namespace: labs-ci-cd
    dev_namespace: tom-dev
    test_namespace: tom-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
